In [82]:
import pandas as pd
import seaborn as sns

In [83]:
# Carregar o dataset
df = sns.load_dataset("tips")

In [84]:
# Analisar o DataFrame
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

# Análise de Dados numa Nutshell
No processo de análise de dados, podemos contar com 4 grandes pontos, são eles:
- Carregar e Explorar os Dados
- Selecionar / Filtrar os Dados
- Transformar os Dados
- Agregar os Dados

In [85]:
# Nota: Se colocarmos valores soltos, o último é sempre impresso
7
8
print(9)
"Diogo"
"Telemóvel"
"Café"
400

9

400

# Explorar os Dados

In [86]:
# Olhar diretamente para os dados
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [87]:
# Mostrar os primeiros dados
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [88]:
# Mostrar os últimos dados
df.tail(3)

     total_bill   tip     sex smoker   day    time  size
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [89]:
# Número de linhas e colunas
df.shape

(244, 7)

In [90]:
# Tipos de Dados
df.dtypes

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

In [91]:
# Análise Descritiva do dataset - Resumo estatístico rápido
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [92]:
# Dados aleatórios
df.sample(5)

     total_bill   tip     sex smoker   day    time  size
139       13.16  2.75  Female     No  Thur   Lunch     2
54        25.56  4.34    Male     No   Sun  Dinner     4
115       17.31  3.50  Female     No   Sun  Dinner     2
200       18.71  4.00    Male    Yes  Thur   Lunch     3
107       25.21  4.29    Male    Yes   Sat  Dinner     2

In [93]:
# Explorar Colunas!
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [94]:
# Selecionar uma única coluna - Series
s_tip = df["tip"]
s_tip.head()

0    1.01
1    1.66
2    3.50
3    3.31
4    3.61
Name: tip, dtype: float64

In [95]:
# A tabela inteira tem o nome de DataFrame
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [96]:
# Obter valores únicos de uma coluna
df["day"].unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, str): ['Thur', 'Fri', 'Sat', 'Sun']

In [97]:
# Obter a quantidade de valores por categoria
df["day"].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

# Seleção e Filtragem

In [98]:
# Podemos selecionar só uma coluna
df["tip"]

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [99]:
# Podemos selecionar várias colunas (se são várias colunas, é um DataFrame)
df[["tip", "sex"]]

      tip     sex
0    1.01  Female
1    1.66    Male
2    3.50    Male
3    3.31    Male
4    3.61  Female
..    ...     ...
239  5.92    Male
240  2.00  Female
241  2.00    Male
242  1.75    Male
243  3.00  Female

[244 rows x 2 columns]

In [100]:
df_tail = df.tail()
df_tail

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [101]:
# Seleciona o elemento com o ID 242 (loc)
df_tail.loc[242]

total_bill     17.82
tip             1.75
sex             Male
smoker            No
day              Sat
time          Dinner
size               2
Name: 242, dtype: object

In [102]:
# Seleciona o primeiro elemento (iloc)
df_tail.iloc[0]

total_bill     29.03
tip             5.92
sex             Male
smoker            No
day              Sat
time          Dinner
size               3
Name: 239, dtype: object

In [103]:
# Boolean Series

# 1. criar o df
meu_df = pd.DataFrame({
    "idade": [40, 30, 20, 20, 50],
    "curso": ["Data Science", "Programação Web", "Programação Web", "Data Science", "Data Science"]
})

meu_df

   idade            curso
0     40     Data Science
1     30  Programação Web
2     20  Programação Web
3     20     Data Science
4     50     Data Science

In [104]:
# Dá um Boolean Series com esta condição
meu_df["idade"] >= 40

0     True
1    False
2    False
3    False
4     True
Name: idade, dtype: bool

In [105]:
meu_df[meu_df["idade"] >= 40]

   idade         curso
0     40  Data Science
4     50  Data Science

In [106]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [107]:
df_smokers = df[df["smoker"] == "Yes"]
df_non_smokers = df[df["smoker"] == "No"]

In [108]:
# Desafio:
# Quem é que dá mais tips? quem fuma ou quem não fuma?
print("Tip média dos fumadores:", df_smokers["tip"].mean())
print("Tip média dos não fumadores:", df_non_smokers["tip"].mean())

Tip média dos fumadores: 3.008709677419355
Tip média dos não fumadores: 2.9918543046357615

# Transformação

In [109]:
# Coluna que mostra a percentagem da gorjeta
df["tip_pct"] = (df["tip"] / df["total_bill"] * 100).round(2)

In [110]:
# df["tip"] = 0

In [ ]:
df

     total_bill   tip     sex smoker   day    time  size  tip_pct
0         16.99  1.01  Female     No   Sun  Dinner     2     5.94
1         10.34  1.66    Male     No   Sun  Dinner     3    16.05
2         21.01  3.50    Male     No   Sun  Dinner     3    16.66
3         23.68  3.31    Male     No   Sun  Dinner     2    13.98
4         24.59  3.61  Female     No   Sun  Dinner     4    14.68
..          ...   ...     ...    ...   ...     ...   ...      ...
239       29.03  5.92    Male     No   Sat  Dinner     3    20.39
240       27.18  2.00  Female    Yes   Sat  Dinner     2     7.36
241       22.67  2.00    Male    Yes   Sat  Dinner     2     8.82
242       17.82  1.75    Male     No   Sat  Dinner     2     9.82
243       18.78  3.00  Female     No  Thur  Dinner     2    15.97

[244 rows x 8 columns]

In [117]:
# Visualizar uma variável numérica em função de uma categórica - Agregação
# Vamos agregar a categórica e ver como se comportam os números de uma outra númerica

df.groupby("day")["tip"].mean()

day
Thur    2.771452
Fri     2.734737
Sat     2.993103
Sun     3.255132
Name: tip, dtype: float64

# Agregação